### ISSUE TITLE
Linked messages in nested json

### ISSUE THREAD

**Issue by taducquang** [kazupon/vue-i18n#1399]
**Module versions (please complete the following information):**
 - `vue`: 2.6.0
 - `vue-i18n`: 8.25.0

**To Reproduce**
```
{
  "web": "GOOD",
  "home_how_it_works_title": "How it works @:web",
  "home_how_it_works_texts": {
    "1": "Website name is @:web",
    "2": "Lorem sumip",
  },
} 
```

**Expected behavior**
@:web in "home_how_it_works_texts"."1" should return "GOOD" but it doesn't, it returns as @:web instead.

**Additional context**
@:web in "home_how_it_works_title" works but not in the nested messages, im not sure how to call it. Would appreciated any helps.

**Comment by vuong-cuong-phoenix** [comment]
Hi, I've just tested in YAML format and it worked perfectly fine:
```yaml
# en.yaml
web: "GOOD"
home_how_it_works_title: "How it works @:web"
home_how_it_works_texts:
  1: "Website name is @:web"
  2: "Lorem sumip"
```

```vue
<!-- TestComponent.vue -->
<template>
    <p>{{ t('web') }}</p>
    <p>{{ t('home_how_it_works_title') }}</p>
    <p>{{ t('home_how_it_works_texts.1') }}</p>
</template>

<script setup>
import { useI18n } from 'vue-i18n';

const { t } = useI18n();
</script>
```

I think you should write the linked message like `@:{'web'}` and see if it works.
