### ISSUE TITLE
TranslateResult type does not accept array

### ISSUE THREAD

**Issue by schrapel** [kazupon/vue-i18n#580]
### vue & vue-i18n version
vue 2.6.10
vue-i18n 8.11.2

### Reproduction Link

My messages
```
countries: [{
    "name": "Afghanistan",
    "code": "AF"
  }, {
    "name": "Åland Islands",
    "code": "AX"
  }]
```

The code I am trying to run
```
this.$t('countries').find((country: Country) => country.code === this.customer.country) 
```

### What is Expected?

No error messages

### What is actually happening?

I get the error message 

`Property 'find' does not exist on type 'TranslateResult'.`

**Comment by exoego** [comment]
How about using messages like
```yaml
en:
  countries:
    AF: Afganistan
    AX: Åland Islands
ja:
  countries:
    AF: アフガニスタン
    AX: オーランド諸島
```

and 

```js
$t(`countries.${this.customer.country}`)
```
