### ISSUE TITLE
Component based localization fallback strategy

### ISSUE THREAD

**Issue by hiendv** [kazupon/vue-i18n#729]
### vue & vue-i18n version
vue: 2.6.10
vue-i18n: 8.15.0

### Reproduction Link

https://jsfiddle.net/3ecmy85g/

### Steps to reproduce
- Run the JSFiddle.
- Comment/Uncomment Line 3 of Javascript for the difference between actual and expected behavior.
### What is Expected?
`message.foo: Phu` since it does exist in the root message with locale `vi`

### What is actually happening?
`message.foo: Foo` because `vue-i18n` checks for fallbackLocale instead of existing `vi` path in the root instance.

**Comment by kazupon** [comment]
Thank you for your reporting!

>Right now, the step 2 and 3 are swapped.

In vue-i18n, actually, steps 2 and 3 are not swapped.

However, In Component based localization, `fallbackLocale` currently inherit from root VueI18n instance.
In about uncomment Line 3 case, VueI18n instance of component Inherits
default value `en-US` of` fallbacks Locale` from root VueI18n instance.

```
## States
component:
  locale: `vi`
  fallbackLocale: 'en-US`
root:
  locale: `vi`
  fallbackLocale: 'en-US`

## Befaivor
1. component locale `vi`: missing
1. component fallbackLocale `en-US`: missing
1. root locale `vi`: translate! 
```
